/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../src/app/app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['App Component'])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['Hellooo'])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['helloooo'])),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['that']))],(null as any),
      (null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(114688,(null as any),0,i2.AppComponent,([] as any[]),(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i2.AppComponent> = i1.ɵccf('my-app',
    i2.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3J5YW5sZXNzb24vRG9jdW1lbnRzL2xlc3Nvbi1vbi1jb2RpbmcvYW5ndWxhci13ZWJwYWNrLXN0YXJ0ZXIvQW5ndWxhci13ZWJwYWNrLXN0YXJ0ZXIvc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3J5YW5sZXNzb24vRG9jdW1lbnRzL2xlc3Nvbi1vbi1jb2RpbmcvYW5ndWxhci13ZWJwYWNrLXN0YXJ0ZXIvQW5ndWxhci13ZWJwYWNrLXN0YXJ0ZXIvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvcnlhbmxlc3Nvbi9Eb2N1bWVudHMvbGVzc29uLW9uLWNvZGluZy9hbmd1bGFyLXdlYnBhY2stc3RhcnRlci9Bbmd1bGFyLXdlYnBhY2stc3RhcnRlci9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3J5YW5sZXNzb24vRG9jdW1lbnRzL2xlc3Nvbi1vbi1jb2RpbmcvYW5ndWxhci13ZWJwYWNrLXN0YXJ0ZXIvQW5ndWxhci13ZWJwYWNrLXN0YXJ0ZXIvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5BcHAgQ29tcG9uZW50PC9oMT5cbjxwPkhlbGxvb288L3A+XG48cD5oZWxsb29vbzwvcD5cbjxwPnRoYXQ8L3A+IiwiPG15LWFwcD48L215LWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBLG1DQUFrQjtNQUN0QjtVQUFBLDBEQUFHO1VBQUEsY0FBVyx1Q0FDZDtVQUFBO1VBQUEsOEJBQUc7TUFBWSx1Q0FDZjtVQUFBO1VBQUEsZ0JBQUc7Ozs7b0JDSEg7TUFBQTthQUFBOztRQUFBOzs7OyJ9
